### ISSUE TITLE
Does not build with upcoming Go 1.22

### ISSUE THREAD

**Issue by stefanb** [grafana/agent#6138]
### What's wrong?

When attempting to build with Go 1.22rc1 it fails to build.

Noticed with  v0.38.1 in 
* https://github.com/Homebrew/homebrew-core/pull/157782

### Steps to reproduce

1. Install Go 1.22rc1
2. Run `make binaries`
3. See build error:

````
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.3/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.3/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
````

### System information

All, irrelevant

### Software version

Grafana Agent v0.39.0

### Configuration

```text
No special config, just building using default `Makefile`.
```
