### PR TITLE
Bump grafana/pyroscope-go to v0.1.6 to support Go 1.22

### LINKED ISSUE #6138: Does not build with upcoming Go 1.22
### What's wrong?

When attempting to build with Go 1.22rc1 it fails to build.

Noticed with  v0.38.1 in 
* https://github.com/Homebrew/homebrew-core/pull/157782

### Steps to reproduce

1. Install Go 1.22rc1
2. Run `make binaries`
3. See build error:

````
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.3/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.3/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
````

### System information

All, irrelevant

### Software version

Grafana Agent v0.39.0

### Configuration

```text
No special config, just building using default `Makefile`.
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by stefanb**
#### PR Description

Bump a dependancy `github.com/grafana/pyroscope-go` to v0.1.6, which supports Go 1.22 since https://github.com/grafana/pyroscope-go/pull/55.

#### Which issue(s) this PR fixes

* fixes #6138

#### PR Checklist

- [x] CHANGELOG.md updated

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]

**Comment by tpaschalis** [comment]
Thanks for the catch and the fix Štefan!

**Comment by stefanb** [comment]
Tnx for merging! Please don't forget to tag a release >v0.39.0 in a near future so that this can be seamlessly picked up elsewhere.
